# Generated by Django 5.2.6 on 2026-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_medicalrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.AddField(
            model_name='billing',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
