# Generated by Django 5.2.6 on 2026-01-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_resource'),
        ('patientapp', '0006_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.location'),
        ),
    ]
