# Generated by Django 5.2.6 on 2026-01-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_appointment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.appointment'),
        ),
    ]
