# Generated by Django 5.2.6 on 2026-01-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_medicalrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_info',
        ),
    ]
